# -*- coding: utf-8 -*-
"""Grammatical_Error.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bP_6Ahehg0QGjvEOYvnBcqb8hELivjHL
"""

pip install nltk language_tool_python PyDictionary

with open('test1.txt', 'r') as file:
    text = file.read()

import language_tool_python

def check_grammar(text):
    tool = language_tool_python.LanguageTool('en-US')
    matches = tool.check(text)
    for match in matches:
        print(match)

check_grammar(text)

